### PR TITLE
Midproject

### PR DESCRIPTION
**Pull request by dhansreeS**
run.py links to src/data_models.py, load_data.py and clean_data.py

Please review the above files.

### CODE REVIEW

**Comment by dhansreeS** [comment]
Feedback for clean_data.py

**Comment by dhansreeS** [comment]
Feedback for data_model.py

**Comment by dhansreeS** [comment]
Feedback for load_data.py

**Comment by dhansreeS** [comment]
Feedback for config.py

**Comment by dhansreeS** [comment]
Feedback for run.py

**Comment by spartan07** [comment]
> Feedback for clean_data.py

**Comment by spartan07** [comment]
> Feedback for clean_data.py

**Comment by spartan07** [comment]
> Feedback for clean_data.py



> Feedback for config.py

Use YAML files to change config and import YAML in config.py rather than editing config file directly!

**Comment by spartan07** [comment]
Unable to use export commands in windows environment!. What should a windows user do?

**Comment by spartan07** [comment]
> Unable to use export commands in windows environment!. What should a windows user do?

Can you take in RDS credentials as user input instead of environment variables

**Comment by dhansreeS** [comment]
> > Feedback for clean_data.py
> 
> > Feedback for config.py
> 
> Use YAML files to change config and import YAML in config.py rather than editing config file directly!

Will change to YAML. Thanks!

**Comment by dhansreeS** [comment]
> Unable to use export commands in windows environment!. What should a windows user do?

Switch to Mac. jk. Will give them the option to enter it through the command line. Thanks for the suggestion!

**Comment by spartan07** [comment]
> Feedback for data_model.py

Move connection type etc to config settings.
Add exception handling while creating databases

**Comment by spartan07** [comment]
> run.py links to src/data_models.py, load_data.py and clean_data.py
> 
> Please review the above files.

Add exception handling whenever interacting with S3,RDS

**Comment by spartan07** [comment]
> Feedback for clean_data.py

Please include test cases for this module!

**Comment by dhansreeS** [comment]
> Add exception handling while creating databases

Thanks! Will add the exception handling. Any reason for the connection type to be in the config file?

**Comment by dhansreeS** [comment]
> > run.py links to src/data_models.py, load_data.py and clean_data.py
> > Please review the above files.
> 
> Add exception handling whenever interacting with S3,RDS

Added. Thanks for the recommendation!

**Comment by dhansreeS** [comment]
> > Feedback for clean_data.py
> 
> Please include test cases for this module!

Thanks for pointing it out! Added testing

**Comment by spartan07** [comment]
Looks great!

**Pull request merged**
